// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKIJSYJyRHgikLrjtz3Ywxf9qjR54ZgKk',
    appId: '1:384865727065:android:baeac3b02fe9824b68f748',
    messagingSenderId: '384865727065',
    projectId: 'organizame-6649a',
    storageBucket: 'organizame-6649a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChmnksVqqgCilA0_BOFJH6z8kNXo-3jNE',
    appId: '1:384865727065:ios:2f7992f18f9eca4f68f748',
    messagingSenderId: '384865727065',
    projectId: 'organizame-6649a',
    storageBucket: 'organizame-6649a.appspot.com',
    androidClientId: '384865727065-k00o03oj3anu4pqk0bqa56h4rdgum285.apps.googleusercontent.com',
    iosClientId: '384865727065-om8edbjjr8uecrtb3f79bgojd80jghmn.apps.googleusercontent.com',
    iosBundleId: 'br.edu.upf.organizame',
  );

}